title: FRACTALWARE
author:
  name: FRACTALWARE
  email: fractalware@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Game Development

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: fractalware
    facebook: fractalwarestudios
    youtube: fractalware
    # github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    #
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: "https://www.youtube.com/channel/UCmKG0Je5leyrqkRilYwQ3TQ?"
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - games.markdown
 - blog.markdown
 - about.markdown
 - contact.markdown

# Build settings
theme: minima

minima:
 skin: dark

plugins:
 - jekyll-feed
 - jekyll-seo-tag



#


